### PR TITLE
MBS-6453: Avoid submission of question form when clicking GGB buttons

### LINKED ISSUE #57: Question preview submit does not work in moodle 4
When previewing a question of qtype_geogebra in moodle 4 (tested on 4.0.1+, 2022041901.02) with an authoring role a click on button "Check"or on "Submit and finish" has **no effect**: No reload is being triggered. There is no warning or error on the console.
In a quiz activity the questions are evaluated correctly.

Bildschirmfoto_2022-05-25_09-23-15

### LINKED ISSUE #63: Page reloads triggered by some options in the applet
Hi everyone,

we are currently creating Moodle courses. Some of these courses need the full GeoGebra functionality. However, some actions such as opening the menu or adding text trigger a complete page reload. That makes these options quite unusable in these contexts. Could you please look into this problem, or at least give us a hint about what is likely causing this so we can tackle it ourselves (we would certainly commit our bugifxes)? I uploaded a video on Youtube demonstrating the issue: [https://youtu.be/qGZ5Gwi62WA](url)

Best,
Sebastian Gombert

### PR DESCRIPTION
**Pull request by PhMemmel**
Closes #63 
Closes #57 

Care: This PR also includes the change suggested in #57.

Implementation details: I use a Mutation Observer to track the adding of button elements in the GGB applet itself and convert all of the buttons (which are by default 'submit' buttons) to standard buttons (type 'button'), so they will not trigger a form submission.

This is not an optimal approach, but trying to catch the event and prevent the submission in certain cases has other downsides, see #63 for details.

### CODE REVIEW

**Comment by murkle** [comment]
@PhMemmel We will change the button type to "button" in GeoGebra (so you won't need the hack 😄 )

ref APPS-4099

**Comment by PhMemmel** [comment]
@murkle Awesome, thank you! Please make sure you catch every button ;-)

**Comment by PhMemmel** [comment]
Closed, will be solved in GGB app itself.

**Comment by murkle** [comment]
Please test with v719 (not released yet)
`    applet.setHTML5Codebase("https://www.geogebra.org/apps/5.0.498.0/web3d");
`

**Pull request closed without merging**
